### ISSUE TITLE
Don't work on Nexus 5 

### ISSUE THREAD

**Issue by misha-plus** [RichyHBM/Monochromatic#9]
Hello.
The idea of the app is good.
I have granted permissions through ADB. Enabled monochromatic mode through the app but colors still exist. 

My android is Nexus 5 / Android v6.0.1

**Comment by RichyHBM** [comment]
Have you changed any of the options in settings to give it a trigger? Always on, time based, battery level...

**Comment by misha-plus** [comment]
Thank you!
With "Always on" the app is working.

**Comment by cvzi** [comment]
I think this is bug. 
If you install the app and follow the adb instructions and then hit the master switch, nothing happens, that's very confusing. I already uninstalled the app, because I thought it does not work.

I suggest to either enable "Always on" as default or describe the behavior on the main activity. A normal user does not know that a "trigger" is required.

**Comment by RichyHBM** [comment]
That is a very good point, in the next version (hopefully out tonight on the play store and a little later on f-droid) I have changed it to always on by default and added some text to the main page informing to change it in settings

I also found it was hard to tell when it has worked as the app is pretty monochrome itself, so I have added some colour to the app name header
